version: 2
project_name: drime-shell

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/drime
    binary: drime-shell
    ldflags:
      - -s -w -X github.com/gYonder/drime-shell/internal/build.Version={{.Version}} -X github.com/gYonder/drime-shell/internal/build.Commit={{.Commit}} -X github.com/gYonder/drime-shell/internal/build.Date={{.Date}}

archives:
  - format: tar.gz
    # this name template makes the tarballs compatible with standard install scripts
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'

release:
  # Always mark as latest release (even for pre-releases like beta)
  make_latest: true
